# Site settings
locale: "en-US"
title: "WOCATI"
title_separator: "-"
subtitle: "World Conference of Associated Theological Institutions"
email: hello@wocati.org
description: >- # this means to ignore newlines until "baseurl:"
  "World Conference of Associated Theological Institutions (WOCATI) is a global network to serve, support, and enhance theological education around the World."
twitter_username: WOCATI
search: true
search_provider: pagefind
url: "https://www.wocati.org"
teaser: "/images/teaser.png"
logo: "/images/international-88x88.png"
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "UTC" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: true # true, false (default)
words_per_minute: 200

analytics:
  provider: false

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/WOCATI"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/WOCATI/"
    - label: "Website"
      icon: "fas fa-fw fa-globe"
      url: "https://adamdjbrett.com"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # assets
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "wp-content/uploads"
    values:
      pdf: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
